"""upgrade...

Revision ID: 84eceabbf846
Revises: d44cadfa60f5
Create Date: 2023-12-17 13:46:05.332607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84eceabbf846'
down_revision: Union[str, None] = 'd44cadfa60f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_status_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'status', ['status_id'], ['id'])
    op.drop_column('product', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_status_fkey', 'product', 'status', ['status'], ['id'])
    op.drop_column('product', 'status_id')
    # ### end Alembic commands ###
