"""upgrade..

Revision ID: d44cadfa60f5
Revises: e4c238831a41
Create Date: 2023-12-17 13:38:01.438440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44cadfa60f5'
down_revision: Union[str, None] = 'e4c238831a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('subcategory_subcategory_fkey', 'subcategory', type_='foreignkey')
    op.create_foreign_key(None, 'subcategory', 'category', ['category_id'], ['id'])
    op.drop_column('subcategory', 'subcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('subcategory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subcategory', type_='foreignkey')
    op.create_foreign_key('subcategory_subcategory_fkey', 'subcategory', 'category', ['subcategory'], ['id'])
    op.drop_column('subcategory', 'category_id')
    # ### end Alembic commands ###
